language: node_js
node_js:
  - 12
script:
  - npm test
before_deploy:
  - npm run package
deploy:
  - provider: releases
    token:
      secure: BLoxrPBhc4KUtAlq4KBKOcQPVPPM9uusBqyfg4MAgar+6TH1dOdyWpgu+t5FJvL2cx/1xRz7xtvyHIbTnosvZiA4PSbUSyCmP/LeGACmnieXKvGEV/nTovaxgyoxcAQw7lZEhYrlLiyk+EPHgPKAKRmLDnoZ8AtLMcndd3mV9oR85JpDdgIKBSaaApRMiZ/t5PxyVbGGWpb8oFMH1STqIxeHhB9gmkU8KeUshif48cOvZmEHAW/F4CzYT9nb0qj696AY29NUA98fZHyRfZaxfm7O7bAzr1w2Xht266CLEeeVSUuJ0vxoPI2QYckdhq8uVK1fav3dXA/FKctDh/fVr/kX4V05ZPcRdvVQygRbMZxR2jY9SaqrbQtXivHUm2elAPGMqkJjlNT7xsTf1vjiajr4NAzDibsqA74LPEROmFRgewdZqiBy2hs5VMf7Y2aTOJOT790idrWOA/YVcyCpM57DC3wqx22rAkVSAhGgTDg1MoMNaf09CgjHABzlTMU8ijPI7SwIO3O6KObS4LI7x/Lf/AgBJBmphm1v+aiHKa7qZE49U395ofTvYoUtfLIpzgFMjkQQJcNh2dEnrH+gSCT0St1LbX0JhrdxuXCsW19LonZNju9dobB1c5rJvRooGZHDiR9HinSflXzSvgT+FAeswQ4u+5LgDP1fmcA7Dzc=
    file_glob: true
    file: dist/*
    skip_cleanup: true
    on:
      repo: selamanse/alexa-skill-willis-sprechapparat
      tags: true
  - provider: lambda
    function_name: "Turner"
    region: "eu-west-1"
    role: "arn:aws:iam::134174638311:role/CustomAWSLambdaWriteLogs"
    runtime: "nodejs16.x"
    handler_name: "handler"
    access_key_id: "AKIAIFISK53W4EIWYDQQ"
    publish: true
    zip: ./dist
    secret_access_key:
      secure: ZrzmigFbaUkixdu6ZiFHlyhPvfozCEk0QmdORqmFCmxgGIpwrk63Sg+kQOe2oKNV0pXGXDIEe0zn1NPTdSDuIQX1zdN8J2GGR17fuy+G7wYNadfDoAbimlMQ2m84yhZQ8U3HJzZnUAo4lIoEOhvYAb+8bimH8XEHv8fUHqpZEXDd0RXugCelUjPSojgeq1t7iqH7xn1KiRjwivWCtF+5F4W6kZaLn9yEIRfRDP40GgNrBcGIbGhxZ6O0ccDCmPKvHMunCvW1OZ6I3xR0LasrY4MQ9KopkMxajI0N6a3yqDKQAqNHhCtrzO2baOyrn5yBnOlSGkmq5D9/qOQcR3UXKVu/YggTi9q0IQmwen2kS7m2baGGTmfdPYsj3joMC2Ct/WRqMn+bcc5KYZgmqWse3K3ojPqHyjhsaSpkZNEZ0STMOXS/skiRWBzt3fUAiWXQNIJRLPMP3wuhI6yQZ2qmkRA9BR5lcmNkEKb3h4wE/oR66p8sge/wQr+VlApdO9YG1yP8pj5Xr26SUFuNlf95iso3ky2+nE4cbDSoCcyX96RTermhP0yBoRuq4L04nCsU6TWjzxZtWuSyn6F83Fz4U9dY19GrSWpKFwcflq4AW1aEjjJO6OMjPfz9Qr9QHFVA0M1E1eiID2zOMbYthfvm8nt88JleuLmhs+9iTLwKlwk=
    on:
      repo: selamanse/alexa-skill-willis-sprechapparat
      tags: true
