name: 'publish'

on:
  push:
    tags:
      - '*'
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

defaults:
  run:
    shell: bash

jobs:
  publish:
    name: 'publish-and-deploy'
    runs-on: ubuntu-latest
    steps:
      #checkout and build
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm test
      - run: npm run package

      - name: Release
        uses: fnkr/github-action-ghr@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_PATH: dist/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy lambda
        uses: appleboy/lambda-action@master
        if: startsWith(github.ref, 'refs/tags/')
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: eu-west-1
          function_name: Turner
          zip_file: dist/function.zip
          memory_size: 128
          timeout: 10
          handler: index.handler
          role: arn:aws:iam::134174638311:role/CustomAWSLambdaWriteLogs
          runtime: nodejs16.x