name: 'publish'

on:
  push:
    tags:
      - '*'

defaults:
  run:
    shell: bash

jobs:
  publish:
    name: 'publish-and-deploy'
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository to the GitHub Actions runner
      - uses: actions/checkout@v2

      - name: Release
        uses: fnkr/github-action-ghr@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_PATH: dist/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy lambda
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: eu-west-1
          function_name: Turner
          zip_file: dist/function.zip
          memory_size: 128
          timeout: 10
          handler: foobar
          role: arn:aws:iam::134174638311:role/CustomAWSLambdaWriteLogs
          runtime: nodejs16.x